apiVersion: apps/v1beta1
kind: Deployment
metadata:
    namespace: nsdev
    name: @KAPP_NAME
    labels:
        app: @KAPP_NAME
spec:
    template:
        metadata:
            labels:
                app: @KAPP_NAME
                tier: web
        spec:
            containers:
                - name: @KAPP_NAME
                  image: khawarhere/@KAPP_NAME:@KVERSION
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    namespace: nsdev
    name: @KAPP_NAME
    labels:
        app: @KAPP_NAME
spec:
    type: NodePort
    selector:
        app: @KAPP_NAME
        tier: web
    ports:
        - port: 80
          targetPort: 80

#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  namespace: nsdev
#  name: @KAPP_NAME
#  labels:
#    app: @KAPP_NAME
#spec:
#  template:
#    metadata:
#      labels:
#        app: @KAPP_NAME
#        tier: web
#    spec:
##      imagePullSecrets:
##      - name: gitlab-auth
#      containers:
#      - name: @KAPP_NAME
#        image: khawarhere/@KAPP_NAME:@KVERSION
#        ports:
#        - containerPort: 8080
#        env:
#          - name: DB_USER
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: db_user
#          - name: DB_PASSWORD
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: db_password
#          - name: DB_HOST
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: db_host
#          - name: DB_NAME
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: db_name
#          - name: DB_DDL_AUTO
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: db_ddl_auto
#          - name: APP_URL
#            valueFrom:
#              configMapKeyRef:
#                name: app-config
#                key: app_url
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: nsdev
#  name: @KAPP_NAME
#  labels:
#    app: @KAPP_NAME
#spec:
#  type: NodePort
#  selector:
#    app: @KAPP_NAME
#    tier: web
#  ports:
#  - port: 8080
#    targetPort: 8080
